merge_queue:
  max_parallel_checks: 2
queue_rules:
  - name: vm1-mq-trusted-push-readonly
    batch_size: 1
    batch_max_wait_time: 1 min
    max_checks_retries: 1
    queue_conditions:
      - title = VM1_MQ_TRUSTED_PUSH_READONLY_260923
    merge_conditions:
      - check-success = vm1-mq-never
    merge_method: squash
pull_request_rules: []
merge_protections_settings:
  auto_merge_conditions: true
